# edna-dada2 configuration file
#
# Follows Kevin/Pete's SK18S example
#
# required:  email, input_path, output_path
# all other values have defaults if unspecified
# verbose can be trace, debug, info (default), warn, error, fatal.  Only messages
#   at or above severity of verbosity level are output (to console and log)
version: v0.001
email: "btupper@bigelow.org"
input_path: "/home/btupper/edna/data/examples/SK18S"
output_path: "/home/btupper/edna/data/examples/SK18S_results"
verbose: info
multithread: 24
dada2_plotQualityProfile:
  nplots: 2
dada2_filterAndTrim_filtN:
  name: "filtN"
  truncLen: 
  - 275
  - 225
  maxN: 0.0
  maxEE:
  - 2
  - 2
  truncQ: 2
  rm.phix: yes
  compress: yes
dada2_learnErrors:
  name: "learnErrors"
cutadapt:
  app: "/mnt/modules/bin/dada2/1.12/bin/cutadapt"
  more_args: "--minimum-length 25.0 -n 2.0"
dada2_filterAndTrim_filtered:
  name: "filtered"
  truncLen: 
  - 275
  - 225
  maxN: 0.0
  maxEE:
  - 2
  - 2
  truncQ: 2
  rm.phix: yes
  compress: yes
dada2_dada_filtered:
  name: "dada"
dada2_removeBimeraDenovo_seqtab:
  method: "consensus"
  verbose: yes
dada2_assignTaxonomy_nochim:
  refFasta: "/home/btupper/edna/data/examples/pr2_version_4.12.0_18S_dada2.fasta"
  minBoot: 0
  outputBootstraps: yes
  verbose: yes
  taxLevels:
  - "Kingdom"
  - "Supergroup"
  - "Division"
  - "Class"
  - "Order"
  - "Family"
  - "Genus"
  - "Species"
primer:
  FWD: "CYGCGGTAATTCCAGCTC"
  REV: "AYGGTATCTRATCRTCTTYG"

